# -*- coding: utf-8 -*-

#########################################################################
## Provisionamento SPA2102
#########################################################################

def escreve_spa2102(dado):
	print "%s - %s" %(dado.prov_equipamento.modelo, dado.prov_mac.mac)
	con2=db((Prov_mac.id == Prov_ramal.id_mac) & (Prov_mac.mac == dado.prov_mac.mac)).count()
	print con2

	arq = open('/var/www/provisionamento/%s.cfg'%(dado.prov_mac.mac),'w')

	arq.write("<?xml version='1.0'?>\n")
	arq.write("<!-- Provisining SPA2102 -->\n")
	arq.write("<flat-profile>\n")
	arq.write("<Restricted_Access_Domains></Restricted_Access_Domains>\n")
	arq.write("<Enable_Web_Admin_Access>Yes</Enable_Web_Admin_Access>\n")
	arq.write("<IVR_Admin_Passwd></IVR_Admin_Passwd>\n")
	arq.write("<Network_Startup_Delay>3</Network_Startup_Delay>\n")
	arq.write("<DNS_Query_TTL_Ignore>No</DNS_Query_TTL_Ignore>\n")
	arq.write("<Syslog_Server></Syslog_Server>\n")
	arq.write("<Debug_Server></Debug_Server>\n")
	arq.write("<Debug_Level>3</Debug_Level>\n")
	arq.write("<Provision_Enable>Yes</Provision_Enable>\n")
	arq.write("<Resync_On_Reset>Yes</Resync_On_Reset>\n\n")

	arq.write("<Resync_Random_Delay>2</Resync_Random_Delay>\n")
	arq.write("<Resync_At__HHmm_></Resync_At__HHmm_>\n")
	arq.write("<Resync_At_Random_Delay>600</Resync_At_Random_Delay>\n")
	arq.write("<Resync_Periodic>3600</Resync_Periodic>\n")
	arq.write("<Resync_Error_Retry_Delay>3600</Resync_Error_Retry_Delay>\n")
	arq.write("<Forced_Resync_Delay>14400</Forced_Resync_Delay>\n")
	arq.write("<Resync_From_SIP>Yes</Resync_From_SIP>\n")
	arq.write("<Resync_After_Upgrade_Attempt>Yes</Resync_After_Upgrade_Attempt>\n")
	arq.write("<Resync_Trigger_1></Resync_Trigger_1>\n")
	arq.write("<Resync_Trigger_2></Resync_Trigger_2>\n\n")

	arq.write("<Resync_Fails_On_FNF>Yes</Resync_Fails_On_FNF>\n")
	arq.write("<Profile_Rule>http://%s/provisionamento/%s.cfg</Profile_Rule>\n" %(dado.prov_rede.proxy, dado.prov_mac.mac))
	arq.write("<Profile_Rule_B></Profile_Rule_B>\n")
	arq.write("<Profile_Rule_C></Profile_Rule_C>\n")
	arq.write("<Profile_Rule_D></Profile_Rule_D>\n")
	arq.write("<Log_Resync_Request_Msg>$PN $MAC -- Requesting resync $SCHEME://$SERVIP:$PORT$PATH</Log_Resync_Request_Msg>\n")
	arq.write("<Log_Resync_Success_Msg>$PN $MAC -- Successful resync $SCHEME://$SERVIP:$PORT$PATH</Log_Resync_Success_Msg>\n")
	arq.write("<Log_Resync_Failure_Msg>$PN $MAC -- Resync failed: $ERR</Log_Resync_Failure_Msg>\n")
	arq.write("<Report_Rule></Report_Rule>\n")
	arq.write("<SP_Default></SP_Default>\n")
	arq.write("<Upgrade_Enable>Yes</Upgrade_Enable>\n\n")

	arq.write("<Upgrade_Error_Retry_Delay>3600</Upgrade_Error_Retry_Delay>\n")
	arq.write("<Downgrade_Rev_Limit></Downgrade_Rev_Limit>\n")
	arq.write("<Upgrade_Rule></Upgrade_Rule>\n")
	arq.write("<Log_Upgrade_Request_Msg>$PN $MAC -- Requesting upgrade $SCHEME://$SERVIP:$PORT$PATH</Log_Upgrade_Request_Msg>\n")
	arq.write("<Log_Upgrade_Success_Msg>$PN $MAC -- Successful upgrade $SCHEME://$SERVIP:$PORT$PATH -- $ERR</Log_Upgrade_Success_Msg>\n")
	arq.write("<Log_Upgrade_Failure_Msg>$PN $MAC -- Upgrade failed: $ERR</Log_Upgrade_Failure_Msg>\n")
	arq.write("<License_Keys></License_Keys>\n")
	arq.write("<Recovery_URL></Recovery_URL>\n")
	arq.write("<Custom_CA_URL></Custom_CA_URL>\n")
	arq.write("<GPP_A></GPP_A>\n")
	arq.write("<GPP_B></GPP_B>\n")
	arq.write("<GPP_C></GPP_C>\n")
	arq.write("<GPP_D></GPP_D>\n\n")

	arq.write("<GPP_E></GPP_E>\n")
	arq.write("<GPP_F></GPP_F>\n")
	arq.write("<GPP_G></GPP_G>\n")
	arq.write("<GPP_H></GPP_H>\n")
	arq.write("<GPP_I></GPP_I>\n")
	arq.write("<GPP_J></GPP_J>\n")
	arq.write("<GPP_K></GPP_K>\n")
	arq.write("<GPP_L></GPP_L>\n")
	arq.write("<GPP_M></GPP_M>\n")
	arq.write("<GPP_N></GPP_N>\n")
	arq.write("<GPP_O></GPP_O>\n")
	arq.write("<GPP_P></GPP_P>\n")
	arq.write("<!-- <GPP_SA></GPP_SA> -->\n")
	arq.write("<!-- <GPP_SB></GPP_SB> -->\n")
	arq.write("<!-- <GPP_SC></GPP_SC> -->\n")
	arq.write("<!-- <GPP_SD></GPP_SD> -->\n")
	arq.write("<Max_Forward>70</Max_Forward>\n\n")

	arq.write("<Max_Redirection>5</Max_Redirection>\n")
	arq.write("<Max_Auth>2</Max_Auth>\n")
	arq.write("<SIP_User_Agent_Name>$VERSION</SIP_User_Agent_Name>\n")
	arq.write("<SIP_Server_Name>$VERSION</SIP_Server_Name>\n")
	arq.write("<SIP_Reg_User_Agent_Name></SIP_Reg_User_Agent_Name>\n")
	arq.write("<SIP_Accept_Language></SIP_Accept_Language>\n")
	arq.write("<DTMF_Relay_MIME_Type>application/dtmf-relay</DTMF_Relay_MIME_Type>\n")
	arq.write("<Hook_Flash_MIME_Type>application/hook-flash</Hook_Flash_MIME_Type>\n")
	arq.write("<Remove_Last_Reg>No</Remove_Last_Reg>\n")
	arq.write("<Use_Compact_Header>No</Use_Compact_Header>\n\n")

	arq.write("<Escape_Display_Name>No</Escape_Display_Name>\n")
	arq.write("<RFC_2543_Call_Hold>Yes</RFC_2543_Call_Hold>\n")
	arq.write("<Mark_All_AVT_Packets>Yes</Mark_All_AVT_Packets>\n")
	arq.write("<SIP_TCP_Port_Min>5060</SIP_TCP_Port_Min>\n")
	arq.write("<SIP_TCP_Port_Max>5080</SIP_TCP_Port_Max>\n")
	arq.write("<CTI_Enable>No</CTI_Enable>\n")
	arq.write("<SIP_T1>.5</SIP_T1>\n")
	arq.write("<SIP_T2>4</SIP_T2>\n")
	arq.write("<SIP_T4>5</SIP_T4>\n\n")

	arq.write("<SIP_Timer_B>32</SIP_Timer_B>\n")
	arq.write("<SIP_Timer_F>16</SIP_Timer_F>\n")
	arq.write("<SIP_Timer_H>32</SIP_Timer_H>\n")
	arq.write("<SIP_Timer_D>32</SIP_Timer_D>\n")
	arq.write("<SIP_Timer_J>32</SIP_Timer_J>\n")
	arq.write("<INVITE_Expires>240</INVITE_Expires>\n")
	arq.write("<ReINVITE_Expires>30</ReINVITE_Expires>\n")
	arq.write("<Reg_Min_Expires>1</Reg_Min_Expires>\n")
	arq.write("<Reg_Max_Expires>7200</Reg_Max_Expires>\n\n")

	arq.write("<Reg_Retry_Intvl>30</Reg_Retry_Intvl>\n")
	arq.write("<Reg_Retry_Long_Intvl>1200</Reg_Retry_Long_Intvl>\n")
	arq.write("<Reg_Retry_Random_Delay>0</Reg_Retry_Random_Delay>\n")
	arq.write("<Reg_Retry_Long_Random_Delay>0</Reg_Retry_Long_Random_Delay>\n")
	arq.write("<Reg_Retry_Intvl_Cap>0</Reg_Retry_Intvl_Cap>\n")
	arq.write("<SIT1_RSC></SIT1_RSC>\n")
	arq.write("<SIT2_RSC></SIT2_RSC>\n")
	arq.write("<SIT3_RSC></SIT3_RSC>\n")
	arq.write("<SIT4_RSC></SIT4_RSC>\n")
	arq.write("<Try_Backup_RSC></Try_Backup_RSC>\n")
	arq.write("<Retry_Reg_RSC></Retry_Reg_RSC>\n")
	arq.write("<RTP_Port_Min>16384</RTP_Port_Min>\n\n")

	arq.write("<RTP_Port_Max>16482</RTP_Port_Max>\n")
	arq.write("<RTP_Packet_Size>0.030</RTP_Packet_Size>\n")
	arq.write("<Max_RTP_ICMP_Err>0</Max_RTP_ICMP_Err>\n")
	arq.write("<RTCP_Tx_Interval>0</RTCP_Tx_Interval>\n")
	arq.write("<No_UDP_Checksum>No</No_UDP_Checksum>\n")
	arq.write("<Stats_In_BYE>Yes</Stats_In_BYE>\n")
	arq.write("<NSE_Dynamic_Payload>100</NSE_Dynamic_Payload>\n")
	arq.write("<AVT_Dynamic_Payload>101</AVT_Dynamic_Payload>\n")
	arq.write("<INFOREQ_Dynamic_Payload></INFOREQ_Dynamic_Payload>\n")

	arq.write("<G726r32_Dynamic_Payload>2</G726r32_Dynamic_Payload>\n")
	arq.write("<EncapRTP_Dynamic_Payload>112</EncapRTP_Dynamic_Payload>\n")
	arq.write("<RTP-Start-Loopback_Dynamic_Payload>113</RTP-Start-Loopback_Dynamic_Payload>\n")
	arq.write("<RTP-Start-Loopback_Codec>G711u</RTP-Start-Loopback_Codec>\n")
	arq.write("<NSE_Codec_Name>NSE</NSE_Codec_Name>\n")
	arq.write("<AVT_Codec_Name>telephone-event</AVT_Codec_Name>\n")
	arq.write("<G711u_Codec_Name>PCMU</G711u_Codec_Name>\n")
	arq.write("<G711a_Codec_Name>PCMA</G711a_Codec_Name>\n")
	arq.write("<G726r32_Codec_Name>G726-32</G726r32_Codec_Name>\n")

	arq.write("<G729a_Codec_Name>G729a</G729a_Codec_Name>\n")
	arq.write("<EncapRTP_Codec_Name>encaprtp</EncapRTP_Codec_Name>\n")
	arq.write("<Handle_VIA_received>No</Handle_VIA_received>\n")
	arq.write("<Handle_VIA_rport>No</Handle_VIA_rport>\n")
	arq.write("<Insert_VIA_received>No</Insert_VIA_received>\n")
	arq.write("<Insert_VIA_rport>No</Insert_VIA_rport>\n")
	arq.write("<Substitute_VIA_Addr>No</Substitute_VIA_Addr>\n")
	arq.write("<Send_Resp_To_Src_Port>No</Send_Resp_To_Src_Port>\n")
	arq.write("<STUN_Enable>No</STUN_Enable>\n\n")

	arq.write("<STUN_Test_Enable>No</STUN_Test_Enable>\n")
	arq.write("<STUN_Server></STUN_Server>\n")
	arq.write("<EXT_IP></EXT_IP>\n")
	arq.write("<EXT_RTP_Port_Min></EXT_RTP_Port_Min>\n")
	arq.write("<NAT_Keep_Alive_Intvl>15</NAT_Keep_Alive_Intvl>\n")
	arq.write("<Redirect_Keep_Alive>No</Redirect_Keep_Alive>\n")
	arq.write("<Linksys_Key_System>No</Linksys_Key_System>\n")
	arq.write("<Multicast_Address>224.168.168.168:6061</Multicast_Address>\n")
	arq.write("<Key_System_Auto_Discovery>Yes</Key_System_Auto_Discovery>\n")
	arq.write("<Key_System_IP_Address></Key_System_IP_Address>\n")
	arq.write("<Force_LAN_Codec>none</Force_LAN_Codec>\n")

	arq.write("<Station_Name></Station_Name>\n")
	arq.write("<Line_Enable_1_>Yes</Line_Enable_1_>\n")
	arq.write("<SAS_Enable_1_>No</SAS_Enable_1_>\n")
	arq.write("<SAS_DLG_Refresh_Intvl_1_>30</SAS_DLG_Refresh_Intvl_1_>\n")
	arq.write("<SAS_Inbound_RTP_Sink_1_></SAS_Inbound_RTP_Sink_1_>\n")
	arq.write("<NAT_Mapping_Enable_1_>No</NAT_Mapping_Enable_1_>\n")
	arq.write("<NAT_Keep_Alive_Enable_1_>No</NAT_Keep_Alive_Enable_1_>\n")
	arq.write("<NAT_Keep_Alive_Msg_1_>$NOTIFY</NAT_Keep_Alive_Msg_1_>\n")
	arq.write("<NAT_Keep_Alive_Dest_1_>$PROXY</NAT_Keep_Alive_Dest_1_>\n")
	arq.write("<SIP_ToS_DiffServ_Value_1_>0x68</SIP_ToS_DiffServ_Value_1_>\n")

	arq.write("<SIP_CoS_Value_1_>3</SIP_CoS_Value_1_>\n")
	arq.write("<RTP_ToS_DiffServ_Value_1_>0xb8</RTP_ToS_DiffServ_Value_1_>\n")
	arq.write("<RTP_CoS_Value_1_>6</RTP_CoS_Value_1_>\n")
	arq.write("<Network_Jitter_Level_1_>high</Network_Jitter_Level_1_>\n")
	arq.write("<Jitter_Buffer_Adjustment_1_>Yes</Jitter_Buffer_Adjustment_1_>\n")
	arq.write("<SIP_Transport_1_>UDP</SIP_Transport_1_>\n")
	arq.write("<SIP_Port_1_>5060</SIP_Port_1_>\n")
	arq.write("<SIP_100REL_Enable_1_>No</SIP_100REL_Enable_1_>\n")
	arq.write("<EXT_SIP_Port_1_></EXT_SIP_Port_1_>\n")

	arq.write("<Auth_Resync-Reboot_1_>Yes</Auth_Resync-Reboot_1_>\n")
	arq.write("<SIP_Proxy-Require_1_></SIP_Proxy-Require_1_>\n")
	arq.write("<SIP_Remote-Party-ID_1_>Yes</SIP_Remote-Party-ID_1_>\n")
	arq.write("<SIP_GUID_1_>No</SIP_GUID_1_>\n")
	arq.write("<SIP_Debug_Option_1_>none</SIP_Debug_Option_1_>\n")
	arq.write("<RTP_Log_Intvl_1_>0</RTP_Log_Intvl_1_>\n")
	arq.write("<Restrict_Source_IP_1_>No</Restrict_Source_IP_1_>\n")
	arq.write("<Referor_Bye_Delay_1_>4</Referor_Bye_Delay_1_>\n")
	arq.write("<Refer_Target_Bye_Delay_1_>0</Refer_Target_Bye_Delay_1_>\n")

	arq.write("<Referee_Bye_Delay_1_>0</Referee_Bye_Delay_1_>\n")
	arq.write("<Refer-To_Target_Contact_1_>No</Refer-To_Target_Contact_1_>\n")
	arq.write("<Sticky_183_1_>No</Sticky_183_1_>\n")
	arq.write("<Auth_INVITE_1_>No</Auth_INVITE_1_>\n")
	arq.write("<Reply_182_On_Call_Waiting_1_>No</Reply_182_On_Call_Waiting_1_>\n")
	arq.write("<Use_Anonymous_With_RPID_1_>Yes</Use_Anonymous_With_RPID_1_>\n")
	arq.write("<Use_Local_Addr_In_FROM_1_>No</Use_Local_Addr_In_FROM_1_>\n")
	arq.write("<Blind_Attn-Xfer_Enable_1_>No</Blind_Attn-Xfer_Enable_1_>\n")
	arq.write("<MOH_Server_1_></MOH_Server_1_>\n")

	arq.write("<Xfer_When_Hangup_Conf_1_>Yes</Xfer_When_Hangup_Conf_1_>\n")
	arq.write("<Conference_Bridge_URL_1_></Conference_Bridge_URL_1_>\n")
	arq.write("<Conference_Bridge_Ports_1_>3</Conference_Bridge_Ports_1_>\n")
	arq.write("<Enable_IP_Dialing_1_>No</Enable_IP_Dialing_1_>\n")
	arq.write("<Emergency_Number_1_></Emergency_Number_1_>\n")
	arq.write("<Mailbox_ID_1_></Mailbox_ID_1_>\n")
	arq.write("<Outbound_Proxy_1_></Outbound_Proxy_1_>\n")
	arq.write("<Use_Outbound_Proxy_1_>No</Use_Outbound_Proxy_1_>\n")
	arq.write("<Use_OB_Proxy_In_Dialog_1_>Yes</Use_OB_Proxy_In_Dialog_1_>\n")
	arq.write("<Register_1_>Yes</Register_1_>\n\n")

	arq.write("<Make_Call_Without_Reg_1_>No</Make_Call_Without_Reg_1_>\n")
	arq.write("<Register_Expires_1_>3600</Register_Expires_1_>\n")
	arq.write("<Ans_Call_Without_Reg_1_>No</Ans_Call_Without_Reg_1_>\n")
	arq.write("<Use_DNS_SRV_1_>No</Use_DNS_SRV_1_>\n")
	arq.write("<DNS_SRV_Auto_Prefix_1_>No</DNS_SRV_Auto_Prefix_1_>\n")
	arq.write("<Proxy_Fallback_Intvl_1_>3600</Proxy_Fallback_Intvl_1_>\n")
	arq.write("<Proxy_Redundancy_Method_1_>Normal</Proxy_Redundancy_Method_1_>\n")
	arq.write("<Mailbox_Subscribe_URL_1_></Mailbox_Subscribe_URL_1_>\n")
	arq.write("<Mailbox_Subscribe_Expires_1_>2147483647</Mailbox_Subscribe_Expires_1_>\n\n")

	con3 =db(Prov_ramal.id_mac == dado.prov_mac.id).select()
	for x in con3:
		query=(x.ramal == Ramal_virtual.ramal_virtual) & (Ramal_virtual.ramal_fisico == Fisico.usuario)
		if db(query).isempty():
			arq.write('####RAMAL %s NAO EXISTE#####\n' %(x.ramal))
			return (False, x.ramal)
		aut=db(query).select(Fisico.usuario, Fisico.secret, Ramal_virtual.nome)
		print x
		print aut[0]

		arq.write("<Proxy_%s_>%s</Proxy_%s_>\n" %(x.linha, dado.prov_rede.proxy, x.linha))
		arq.write("<Display_Name_%s_>%s</Display_Name_%s_>\n" %(x.linha, aut[0].f_ramal_virtual['nome'], x.linha))
		arq.write("<User_ID_%s_>%s</User_ID_%s_>\n" %(x.linha, aut[0].fisico_sip_iax['usuario'], x.linha))
		arq.write("<Password_%s_>%s</Password_%s_>\n" %(x.linha, aut[0].fisico_sip_iax['secret'], x.linha))
		arq.write("<Dial_Plan_%s_>(*xx.|#xx.|[3469]11|0|00|[2-9]xxxxxx|1xxx[2-9]xxxxxxS0|xxxxxxxxxxxx.)</Dial_Plan_%s_>\n\n" %(x.linha, x.linha))


	arq.write("<Use_Auth_ID_1_>No</Use_Auth_ID_1_>\n");
	arq.write("<Auth_ID_1_></Auth_ID_1_>\n");
	arq.write("<Resident_Online_Number_1_></Resident_Online_Number_1_>\n");
	arq.write("<SIP_URI_1_></SIP_URI_1_>\n");
	arq.write("<Call_Waiting_Serv_1_>No</Call_Waiting_Serv_1_>\n");
	arq.write("<Block_CID_Serv_1_>No</Block_CID_Serv_1_>\n");
	arq.write("<Block_ANC_Serv_1_>No</Block_ANC_Serv_1_>\n");
	arq.write("<Dist_Ring_Serv_1_>No</Dist_Ring_Serv_1_>\n\n");

	arq.write("<Cfwd_All_Serv_1_>No</Cfwd_All_Serv_1_>\n");
	arq.write("<Cfwd_Busy_Serv_1_>No</Cfwd_Busy_Serv_1_>\n");
	arq.write("<Cfwd_No_Ans_Serv_1_>No</Cfwd_No_Ans_Serv_1_>\n");
	arq.write("<Cfwd_Sel_Serv_1_>No</Cfwd_Sel_Serv_1_>\n");
	arq.write("<Cfwd_Last_Serv_1_>No</Cfwd_Last_Serv_1_>\n");
	arq.write("<Block_Last_Serv_1_>No</Block_Last_Serv_1_>\n");
	arq.write("<Accept_Last_Serv_1_>No</Accept_Last_Serv_1_>\n");
	arq.write("<DND_Serv_1_>No</DND_Serv_1_>\n");
	arq.write("<CID_Serv_1_>No</CID_Serv_1_>\n\n");

	arq.write("<CWCID_Serv_1_>No</CWCID_Serv_1_>\n");
	arq.write("<Call_Return_Serv_1_>No</Call_Return_Serv_1_>\n");
	arq.write("<Call_Redial_Serv_1_>No</Call_Redial_Serv_1_>\n");
	arq.write("<Call_Back_Serv_1_>No</Call_Back_Serv_1_>\n");
	arq.write("<Three_Way_Call_Serv_1_>No</Three_Way_Call_Serv_1_>\n");
	arq.write("<Three_Way_Conf_Serv_1_>No</Three_Way_Conf_Serv_1_>\n");
	arq.write("<Attn_Transfer_Serv_1_>No</Attn_Transfer_Serv_1_>\n");
	arq.write("<Unattn_Transfer_Serv_1_>No</Unattn_Transfer_Serv_1_>\n");
	arq.write("<MWI_Serv_1_>No</MWI_Serv_1_>\n\n");

	arq.write("<VMWI_Serv_1_>No</VMWI_Serv_1_>\n");
	arq.write("<Speed_Dial_Serv_1_>No</Speed_Dial_Serv_1_>\n");
	arq.write("<Secure_Call_Serv_1_>No</Secure_Call_Serv_1_>\n");
	arq.write("<Referral_Serv_1_>No</Referral_Serv_1_>\n");
	arq.write("<Feature_Dial_Serv_1_>No</Feature_Dial_Serv_1_>\n");
	arq.write("<Service_Announcement_Serv_1_>No</Service_Announcement_Serv_1_>\n");
	arq.write("<Reuse_CID_Number_As_Name_1_>No</Reuse_CID_Number_As_Name_1_>\n");
	arq.write("<Preferred_Codec_1_>G711u</Preferred_Codec_1_>\n");
	arq.write("<Second_Preferred_Codec_1_>Unspecified</Second_Preferred_Codec_1_>\n\n");

	arq.write("<Third_Preferred_Codec_1_>Unspecified</Third_Preferred_Codec_1_>\n");
	arq.write("<Use_Pref_Codec_Only_1_>No</Use_Pref_Codec_Only_1_>\n");
	arq.write("<Use_Remote_Pref_Codec_1_>No</Use_Remote_Pref_Codec_1_>\n");
	arq.write("<Codec_Negotiation_1_>Default</Codec_Negotiation_1_>\n");
	arq.write("<G729a_Enable_1_>Yes</G729a_Enable_1_>\n");
	arq.write("<Silence_Supp_Enable_1_>No</Silence_Supp_Enable_1_>\n");
	arq.write("<G726-32_Enable_1_>Yes</G726-32_Enable_1_>\n");
	arq.write("<Silence_Threshold_1_>medium</Silence_Threshold_1_>\n");
	arq.write("<FAX_V21_Detect_Enable_1_>Yes</FAX_V21_Detect_Enable_1_>\n\n");

	arq.write("<Echo_Canc_Enable_1_>Yes</Echo_Canc_Enable_1_>\n");
	arq.write("<FAX_CNG_Detect_Enable_1_>Yes</FAX_CNG_Detect_Enable_1_>\n");
	arq.write("<FAX_Passthru_Codec_1_>G711u</FAX_Passthru_Codec_1_>\n");
	arq.write("<FAX_Codec_Symmetric_1_>Yes</FAX_Codec_Symmetric_1_>\n");
	arq.write("<DTMF_Process_INFO_1_>Yes</DTMF_Process_INFO_1_>\n");
	arq.write("<FAX_Passthru_Method_1_>NSE</FAX_Passthru_Method_1_>\n");
	arq.write("<DTMF_Process_AVT_1_>Yes</DTMF_Process_AVT_1_>\n");
	arq.write("<FAX_Process_NSE_1_>Yes</FAX_Process_NSE_1_>\n");
	arq.write("<DTMF_Tx_Method_1_>Auto</DTMF_Tx_Method_1_>\n\n");

	arq.write("<FAX_Disable_ECAN_1_>No</FAX_Disable_ECAN_1_>\n")
	arq.write("<DTMF_Tx_Mode_1_>Strict</DTMF_Tx_Mode_1_>\n")
	arq.write("<DTMF_Tx_Strict_Hold_Off_Time_1_>70</DTMF_Tx_Strict_Hold_Off_Time_1_>\n")
	arq.write("<FAX_Enable_T38_1_>No</FAX_Enable_T38_1_>\n")
	arq.write("<Hook_Flash_Tx_Method_1_>None</Hook_Flash_Tx_Method_1_>\n")
	arq.write("<FAX_T38_Redundancy_1_>1</FAX_T38_Redundancy_1_>\n")
	arq.write("<FAX_T38_ECM_Enable_1_>Yes</FAX_T38_ECM_Enable_1_>\n")
	arq.write("<FAX_Tone_Detect_Mode_1_>caller or callee</FAX_Tone_Detect_Mode_1_>\n")
	arq.write("<Symmetric_RTP_1_>No</Symmetric_RTP_1_>\n")

	arq.write("<FAX_T38_Return_to_Voice_1_>No</FAX_T38_Return_to_Voice_1_>\n")
	arq.write("<Idle_Polarity_1_>Forward</Idle_Polarity_1_>\n")
	arq.write("<Caller_Conn_Polarity_1_>Forward</Caller_Conn_Polarity_1_>\n")
	arq.write("<Callee_Conn_Polarity_1_>Forward</Callee_Conn_Polarity_1_>\n\n")

	arq.write("<Line_Enable_2_>Yes</Line_Enable_2_>\n")
	arq.write("<SAS_Enable_2_>No</SAS_Enable_2_>\n")
	arq.write("<SAS_DLG_Refresh_Intvl_2_>30</SAS_DLG_Refresh_Intvl_2_>\n")
	arq.write("<SAS_Inbound_RTP_Sink_2_></SAS_Inbound_RTP_Sink_2_>\n\n")

	arq.write("<NAT_Mapping_Enable_2_>No</NAT_Mapping_Enable_2_>\n")
	arq.write("<NAT_Keep_Alive_Enable_2_>No</NAT_Keep_Alive_Enable_2_>\n")
	arq.write("<NAT_Keep_Alive_Msg_2_>$NOTIFY</NAT_Keep_Alive_Msg_2_>\n")
	arq.write("<NAT_Keep_Alive_Dest_2_>$PROXY</NAT_Keep_Alive_Dest_2_>\n")
	arq.write("<SIP_ToS_DiffServ_Value_2_>0x68</SIP_ToS_DiffServ_Value_2_>\n")
	arq.write("<SIP_CoS_Value_2_>3</SIP_CoS_Value_2_>\n")
	arq.write("<RTP_ToS_DiffServ_Value_2_>0xb8</RTP_ToS_DiffServ_Value_2_>\n")
	arq.write("<RTP_CoS_Value_2_>6</RTP_CoS_Value_2_>\n")
	arq.write("<Network_Jitter_Level_2_>high</Network_Jitter_Level_2_>\n\n")

	arq.write("<Jitter_Buffer_Adjustment_2_>Yes</Jitter_Buffer_Adjustment_2_>\n")
	arq.write("<SIP_Transport_2_>UDP</SIP_Transport_2_>\n")
	arq.write("<SIP_Port_2_>5061</SIP_Port_2_>\n")
	arq.write("<SIP_100REL_Enable_2_>No</SIP_100REL_Enable_2_>\n")
	arq.write("<EXT_SIP_Port_2_></EXT_SIP_Port_2_>\n")
	arq.write("<Auth_Resync-Reboot_2_>Yes</Auth_Resync-Reboot_2_>\n")
	arq.write("<SIP_Proxy-Require_2_></SIP_Proxy-Require_2_>\n")
	arq.write("<SIP_Remote-Party-ID_2_>Yes</SIP_Remote-Party-ID_2_>\n")
	arq.write("<SIP_GUID_2_>No</SIP_GUID_2_>\n")
	arq.write("<SIP_Debug_Option_2_>none</SIP_Debug_Option_2_>\n\n")

	arq.write("<RTP_Log_Intvl_2_>0</RTP_Log_Intvl_2_>\n")
	arq.write("<Restrict_Source_IP_2_>No</Restrict_Source_IP_2_>\n")
	arq.write("<Referor_Bye_Delay_2_>4</Referor_Bye_Delay_2_>\n")
	arq.write("<Refer_Target_Bye_Delay_2_>0</Refer_Target_Bye_Delay_2_>\n")
	arq.write("<Referee_Bye_Delay_2_>0</Referee_Bye_Delay_2_>\n")
	arq.write("<Refer-To_Target_Contact_2_>No</Refer-To_Target_Contact_2_>\n")
	arq.write("<Sticky_183_2_>No</Sticky_183_2_>\n")
	arq.write("<Auth_INVITE_2_>No</Auth_INVITE_2_>\n")
	arq.write("<Reply_182_On_Call_Waiting_2_>No</Reply_182_On_Call_Waiting_2_>\n\n")

	arq.write("<Use_Anonymous_With_RPID_2_>Yes</Use_Anonymous_With_RPID_2_>\n")
	arq.write("<Use_Local_Addr_In_FROM_2_>No</Use_Local_Addr_In_FROM_2_>\n")
	arq.write("<Blind_Attn-Xfer_Enable_2_>No</Blind_Attn-Xfer_Enable_2_>\n")
	arq.write("<MOH_Server_2_></MOH_Server_2_>\n")
	arq.write("<Xfer_When_Hangup_Conf_2_>Yes</Xfer_When_Hangup_Conf_2_>\n")
	arq.write("<Conference_Bridge_URL_2_></Conference_Bridge_URL_2_>\n")
	arq.write("<Conference_Bridge_Ports_2_>3</Conference_Bridge_Ports_2_>\n")
	arq.write("<Enable_IP_Dialing_2_>No</Enable_IP_Dialing_2_>\n")
	arq.write("<Emergency_Number_2_></Emergency_Number_2_>\n")
	arq.write("<Mailbox_ID_2_></Mailbox_ID_2_>\n\n")

	arq.write("<Outbound_Proxy_2_></Outbound_Proxy_2_>\n")
	arq.write("<Use_Outbound_Proxy_2_>No</Use_Outbound_Proxy_2_>\n")
	arq.write("<Use_OB_Proxy_In_Dialog_2_>Yes</Use_OB_Proxy_In_Dialog_2_>\n")
	arq.write("<Register_2_>Yes</Register_2_>\n")
	arq.write("<Make_Call_Without_Reg_2_>No</Make_Call_Without_Reg_2_>\n")
	arq.write("<Register_Expires_2_>3600</Register_Expires_2_>\n")
	arq.write("<Ans_Call_Without_Reg_2_>No</Ans_Call_Without_Reg_2_>\n")
	arq.write("<Use_DNS_SRV_2_>No</Use_DNS_SRV_2_>\n")
	arq.write("<DNS_SRV_Auto_Prefix_2_>No</DNS_SRV_Auto_Prefix_2_>\n")

	arq.write("<Proxy_Fallback_Intvl_2_>3600</Proxy_Fallback_Intvl_2_>\n")
	arq.write("<Proxy_Redundancy_Method_2_>Normal</Proxy_Redundancy_Method_2_>\n")
	arq.write("<Mailbox_Subscribe_URL_2_></Mailbox_Subscribe_URL_2_>\n")
	arq.write("<Mailbox_Subscribe_Expires_2_>2147483647</Mailbox_Subscribe_Expires_2_>\n\n")

	arq.write("<Auth_ID_2_></Auth_ID_2_>\n")
	arq.write("<Resident_Online_Number_2_></Resident_Online_Number_2_>\n")
	arq.write("<SIP_URI_2_></SIP_URI_2_>\n\n")

	arq.write("<Call_Waiting_Serv_2_>No</Call_Waiting_Serv_2_>\n")
	arq.write("<Block_CID_Serv_2_>No</Block_CID_Serv_2_>\n")
	arq.write("<Block_ANC_Serv_2_>No</Block_ANC_Serv_2_>\n")
	arq.write("<Dist_Ring_Serv_2_>No</Dist_Ring_Serv_2_>\n")
	arq.write("<Cfwd_All_Serv_2_>No</Cfwd_All_Serv_2_>\n")
	arq.write("<Cfwd_Busy_Serv_2_>No</Cfwd_Busy_Serv_2_>\n")
	arq.write("<Cfwd_No_Ans_Serv_2_>No</Cfwd_No_Ans_Serv_2_>\n")
	arq.write("<Cfwd_Sel_Serv_2_>No</Cfwd_Sel_Serv_2_>\n")
	arq.write("<Cfwd_Last_Serv_2_>No</Cfwd_Last_Serv_2_>\n\n")

	arq.write("<Block_Last_Serv_2_>No</Block_Last_Serv_2_>\n")
	arq.write("<Accept_Last_Serv_2_>No</Accept_Last_Serv_2_>\n")
	arq.write("<DND_Serv_2_>No</DND_Serv_2_>\n")
	arq.write("<CID_Serv_2_>No</CID_Serv_2_>\n")
	arq.write("<CWCID_Serv_2_>No</CWCID_Serv_2_>\n")
	arq.write("<Call_Return_Serv_2_>No</Call_Return_Serv_2_>\n")
	arq.write("<Call_Redial_Serv_2_>No</Call_Redial_Serv_2_>\n")
	arq.write("<Call_Back_Serv_2_>No</Call_Back_Serv_2_>\n")
	arq.write("<Three_Way_Call_Serv_2_>No</Three_Way_Call_Serv_2_>\n\n")

	arq.write("<Three_Way_Conf_Serv_2_>No</Three_Way_Conf_Serv_2_>\n")
	arq.write("<Attn_Transfer_Serv_2_>No</Attn_Transfer_Serv_2_>\n")
	arq.write("<Unattn_Transfer_Serv_2_>No</Unattn_Transfer_Serv_2_>\n")
	arq.write("<MWI_Serv_2_>No</MWI_Serv_2_>\n")
	arq.write("<VMWI_Serv_2_>No</VMWI_Serv_2_>\n")
	arq.write("<Speed_Dial_Serv_2_>No</Speed_Dial_Serv_2_>\n")
	arq.write("<Secure_Call_Serv_2_>No</Secure_Call_Serv_2_>\n")
	arq.write("<Referral_Serv_2_>No</Referral_Serv_2_>\n")
	arq.write("<Feature_Dial_Serv_2_>No</Feature_Dial_Serv_2_>\n\n")

	arq.write("<Service_Announcement_Serv_2_>No</Service_Announcement_Serv_2_>\n")
	arq.write("<Reuse_CID_Number_As_Name_2_>No</Reuse_CID_Number_As_Name_2_>\n")
	arq.write("<Preferred_Codec_2_>G711u</Preferred_Codec_2_>\n")
	arq.write("<Second_Preferred_Codec_2_>Unspecified</Second_Preferred_Codec_2_>\n")
	arq.write("<Third_Preferred_Codec_2_>Unspecified</Third_Preferred_Codec_2_>\n")
	arq.write("<Use_Pref_Codec_Only_2_>No</Use_Pref_Codec_Only_2_>\n")
	arq.write("<Use_Remote_Pref_Codec_2_>No</Use_Remote_Pref_Codec_2_>\n")
	arq.write("<Codec_Negotiation_2_>Default</Codec_Negotiation_2_>\n")
	arq.write("<G729a_Enable_2_>Yes</G729a_Enable_2_>\n\n")

	arq.write("<Silence_Supp_Enable_2_>No</Silence_Supp_Enable_2_>\n")
	arq.write("<G726-32_Enable_2_>Yes</G726-32_Enable_2_>\n")
	arq.write("<Silence_Threshold_2_>medium</Silence_Threshold_2_>\n")
	arq.write("<FAX_V21_Detect_Enable_2_>Yes</FAX_V21_Detect_Enable_2_>\n")
	arq.write("<Echo_Canc_Enable_2_>Yes</Echo_Canc_Enable_2_>\n")
	arq.write("<FAX_CNG_Detect_Enable_2_>Yes</FAX_CNG_Detect_Enable_2_>\n")
	arq.write("<FAX_Passthru_Codec_2_>G711u</FAX_Passthru_Codec_2_>\n")
	arq.write("<FAX_Codec_Symmetric_2_>Yes</FAX_Codec_Symmetric_2_>\n")
	arq.write("<DTMF_Process_INFO_2_>Yes</DTMF_Process_INFO_2_>\n\n")

	arq.write("<FAX_Passthru_Method_2_>NSE</FAX_Passthru_Method_2_>\n")
	arq.write("<DTMF_Process_AVT_2_>Yes</DTMF_Process_AVT_2_>\n")
	arq.write("<FAX_Process_NSE_2_>Yes</FAX_Process_NSE_2_>\n")
	arq.write("<DTMF_Tx_Method_2_>Auto</DTMF_Tx_Method_2_>\n")
	arq.write("<FAX_Disable_ECAN_2_>No</FAX_Disable_ECAN_2_>\n")
	arq.write("<DTMF_Tx_Mode_2_>Strict</DTMF_Tx_Mode_2_>\n")
	arq.write("<DTMF_Tx_Strict_Hold_Off_Time_2_>70</DTMF_Tx_Strict_Hold_Off_Time_2_>\n")
	arq.write("<FAX_Enable_T38_2_>No</FAX_Enable_T38_2_>\n")
	arq.write("<Hook_Flash_Tx_Method_2_>None</Hook_Flash_Tx_Method_2_>\n\n")

	arq.write("<FAX_T38_Redundancy_2_>1</FAX_T38_Redundancy_2_>\n")
	arq.write("<FAX_T38_ECM_Enable_2_>Yes</FAX_T38_ECM_Enable_2_>\n")
	arq.write("<FAX_Tone_Detect_Mode_2_>caller or callee</FAX_Tone_Detect_Mode_2_>\n")
	arq.write("<Symmetric_RTP_2_>No</Symmetric_RTP_2_>\n")
	arq.write("<FAX_T38_Return_to_Voice_2_>No</FAX_T38_Return_to_Voice_2_>\n\n")

	arq.write("<Idle_Polarity_2_>Forward</Idle_Polarity_2_>\n")
	arq.write("<Caller_Conn_Polarity_2_>Forward</Caller_Conn_Polarity_2_>\n")
	arq.write("<Callee_Conn_Polarity_2_>Forward</Callee_Conn_Polarity_2_>\n\n")

	arq.write("<Cfwd_All_Dest_1_></Cfwd_All_Dest_1_>\n")
	arq.write("<Cfwd_Busy_Dest_1_></Cfwd_Busy_Dest_1_>\n")
	arq.write("<Cfwd_No_Ans_Dest_1_></Cfwd_No_Ans_Dest_1_>\n")
	arq.write("<Cfwd_No_Ans_Delay_1_>60</Cfwd_No_Ans_Delay_1_>\n")
	arq.write("<Cfwd_Sel1_Caller_1_></Cfwd_Sel1_Caller_1_>\n")
	arq.write("<Cfwd_Sel1_Dest_1_></Cfwd_Sel1_Dest_1_>\n")
	arq.write("<Cfwd_Sel2_Caller_1_></Cfwd_Sel2_Caller_1_>\n")
	arq.write("<Cfwd_Sel2_Dest_1_></Cfwd_Sel2_Dest_1_>\n")
	arq.write("<Cfwd_Sel3_Caller_1_></Cfwd_Sel3_Caller_1_>\n")
	arq.write("<Cfwd_Sel3_Dest_1_></Cfwd_Sel3_Dest_1_>\n")
	arq.write("<Cfwd_Sel4_Caller_1_></Cfwd_Sel4_Caller_1_>\n")
	arq.write("<Cfwd_Sel4_Dest_1_></Cfwd_Sel4_Dest_1_>\n")
	arq.write("<Cfwd_Sel5_Caller_1_></Cfwd_Sel5_Caller_1_>\n")
	arq.write("<Cfwd_Sel5_Dest_1_></Cfwd_Sel5_Dest_1_>\n")
	arq.write("<Cfwd_Sel6_Caller_1_></Cfwd_Sel6_Caller_1_>\n")
	arq.write("<Cfwd_Sel6_Dest_1_></Cfwd_Sel6_Dest_1_>\n\n")

	arq.write("<Cfwd_Sel7_Caller_1_></Cfwd_Sel7_Caller_1_>\n")
	arq.write("<Cfwd_Sel7_Dest_1_></Cfwd_Sel7_Dest_1_>\n")
	arq.write("<Cfwd_Sel8_Caller_1_></Cfwd_Sel8_Caller_1_>\n")
	arq.write("<Cfwd_Sel8_Dest_1_></Cfwd_Sel8_Dest_1_>\n")
	arq.write("<Cfwd_Last_Caller_1_></Cfwd_Last_Caller_1_>\n")
	arq.write("<Cfwd_Last_Dest_1_></Cfwd_Last_Dest_1_>\n")
	arq.write("<Block_Last_Caller_1_></Block_Last_Caller_1_>\n")
	arq.write("<Accept_Last_Caller_1_></Accept_Last_Caller_1_>\n")
	arq.write("<Speed_Dial_2_1_></Speed_Dial_2_1_>\n")
	arq.write("<Speed_Dial_3_1_></Speed_Dial_3_1_>\n")
	arq.write("<Speed_Dial_4_1_></Speed_Dial_4_1_>\n")
	arq.write("<Speed_Dial_5_1_></Speed_Dial_5_1_>\n")
	arq.write("<Speed_Dial_6_1_></Speed_Dial_6_1_>\n")
	arq.write("<Speed_Dial_7_1_></Speed_Dial_7_1_>\n")
	arq.write("<Speed_Dial_8_1_></Speed_Dial_8_1_>\n")
	arq.write("<Speed_Dial_9_1_></Speed_Dial_9_1_>\n")
	arq.write("<CW_Setting_1_>Yes</CW_Setting_1_>\n\n")

	arq.write("<Block_CID_Setting_1_>No</Block_CID_Setting_1_>\n")
	arq.write("<Block_ANC_Setting_1_>No</Block_ANC_Setting_1_>\n")
	arq.write("<DND_Setting_1_>No</DND_Setting_1_>\n")
	arq.write("<CID_Setting_1_>Yes</CID_Setting_1_>\n")
	arq.write("<CWCID_Setting_1_>Yes</CWCID_Setting_1_>\n")
	arq.write("<Dist_Ring_Setting_1_>Yes</Dist_Ring_Setting_1_>\n")
	arq.write("<Secure_Call_Setting_1_>No</Secure_Call_Setting_1_>\n")
	arq.write("<Message_Waiting_1_>No</Message_Waiting_1_>\n")
	arq.write("<Accept_Media_Loopback_Request_1_>automatic</Accept_Media_Loopback_Request_1_>\n\n")

	arq.write("<Media_Loopback_Mode_1_>source</Media_Loopback_Mode_1_>\n")
	arq.write("<Media_Loopback_Type_1_>media</Media_Loopback_Type_1_>\n")
	arq.write("<Ring1_Caller_1_></Ring1_Caller_1_>\n")
	arq.write("<Ring2_Caller_1_></Ring2_Caller_1_>\n")
	arq.write("<Ring3_Caller_1_></Ring3_Caller_1_>\n")
	arq.write("<Ring4_Caller_1_></Ring4_Caller_1_>\n")
	arq.write("<Ring5_Caller_1_></Ring5_Caller_1_>\n")
	arq.write("<Ring6_Caller_1_></Ring6_Caller_1_>\n")
	arq.write("<Ring7_Caller_1_></Ring7_Caller_1_>\n")
	arq.write("<Ring8_Caller_1_></Ring8_Caller_1_>\n")
	arq.write("<Default_Ring_1_>1</Default_Ring_1_>\n")
	arq.write("<Default_CWT_1_>1</Default_CWT_1_>\n")
	arq.write("<Hold_Reminder_Ring_1_>8</Hold_Reminder_Ring_1_>\n\n")

	arq.write("<Call_Back_Ring_1_>7</Call_Back_Ring_1_>\n")
	arq.write("<Cfwd_Ring_Splash_Len_1_>0</Cfwd_Ring_Splash_Len_1_>\n")
	arq.write("<Cblk_Ring_Splash_Len_1_>0</Cblk_Ring_Splash_Len_1_>\n")
	arq.write("<VMWI_Ring_Policy_1_>New VM Available</VMWI_Ring_Policy_1_>\n")
	arq.write("<VMWI_Ring_Splash_Len_1_>0</VMWI_Ring_Splash_Len_1_>\n")
	arq.write("<Ring_On_No_New_VM_1_>No</Ring_On_No_New_VM_1_>\n")
	arq.write("<Cfwd_All_Dest_2_></Cfwd_All_Dest_2_>\n")
	arq.write("<Cfwd_Busy_Dest_2_></Cfwd_Busy_Dest_2_>\n")
	arq.write("<Cfwd_No_Ans_Dest_2_></Cfwd_No_Ans_Dest_2_>\n")
	arq.write("<Cfwd_No_Ans_Delay_2_>60</Cfwd_No_Ans_Delay_2_>\n\n")

	arq.write("<Cfwd_Sel1_Caller_2_></Cfwd_Sel1_Caller_2_>\n")
	arq.write("<Cfwd_Sel1_Dest_2_></Cfwd_Sel1_Dest_2_>\n")
	arq.write("<Cfwd_Sel2_Caller_2_></Cfwd_Sel2_Caller_2_>\n")
	arq.write("<Cfwd_Sel2_Dest_2_></Cfwd_Sel2_Dest_2_>\n")
	arq.write("<Cfwd_Sel3_Caller_2_></Cfwd_Sel3_Caller_2_>\n")
	arq.write("<Cfwd_Sel3_Dest_2_></Cfwd_Sel3_Dest_2_>\n")
	arq.write("<Cfwd_Sel4_Caller_2_></Cfwd_Sel4_Caller_2_>\n")
	arq.write("<Cfwd_Sel4_Dest_2_></Cfwd_Sel4_Dest_2_>\n")
	arq.write("<Cfwd_Sel5_Caller_2_></Cfwd_Sel5_Caller_2_>\n")
	arq.write("<Cfwd_Sel5_Dest_2_></Cfwd_Sel5_Dest_2_>\n")
	arq.write("<Cfwd_Sel6_Caller_2_></Cfwd_Sel6_Caller_2_>\n")
	arq.write("<Cfwd_Sel6_Dest_2_></Cfwd_Sel6_Dest_2_>\n")
	arq.write("<Cfwd_Sel7_Caller_2_></Cfwd_Sel7_Caller_2_>\n")
	arq.write("<Cfwd_Sel7_Dest_2_></Cfwd_Sel7_Dest_2_>\n")
	arq.write("<Cfwd_Sel8_Caller_2_></Cfwd_Sel8_Caller_2_>\n")
	arq.write("<Cfwd_Sel8_Dest_2_></Cfwd_Sel8_Dest_2_>\n")
	arq.write("<Cfwd_Last_Caller_2_></Cfwd_Last_Caller_2_>\n\n")

	arq.write("<Cfwd_Last_Dest_2_></Cfwd_Last_Dest_2_>\n")
	arq.write("<Block_Last_Caller_2_></Block_Last_Caller_2_>\n")
	arq.write("<Accept_Last_Caller_2_></Accept_Last_Caller_2_>\n")
	arq.write("<Speed_Dial_2_2_></Speed_Dial_2_2_>\n")
	arq.write("<Speed_Dial_3_2_></Speed_Dial_3_2_>\n")
	arq.write("<Speed_Dial_4_2_></Speed_Dial_4_2_>\n")
	arq.write("<Speed_Dial_5_2_></Speed_Dial_5_2_>\n")
	arq.write("<Speed_Dial_6_2_></Speed_Dial_6_2_>\n")
	arq.write("<Speed_Dial_7_2_></Speed_Dial_7_2_>\n")
	arq.write("<Speed_Dial_8_2_></Speed_Dial_8_2_>\n")
	arq.write("<Speed_Dial_9_2_></Speed_Dial_9_2_>\n")
	arq.write("<CW_Setting_2_>Yes</CW_Setting_2_>\n")
	arq.write("<Block_CID_Setting_2_>No</Block_CID_Setting_2_>\n")
	arq.write("<Block_ANC_Setting_2_>No</Block_ANC_Setting_2_>\n\n")

	arq.write("<DND_Setting_2_>No</DND_Setting_2_>\n")
	arq.write("<CID_Setting_2_>Yes</CID_Setting_2_>\n")
	arq.write("<CWCID_Setting_2_>Yes</CWCID_Setting_2_>\n")
	arq.write("<Dist_Ring_Setting_2_>Yes</Dist_Ring_Setting_2_>\n")
	arq.write("<Secure_Call_Setting_2_>No</Secure_Call_Setting_2_>\n")
	arq.write("<Message_Waiting_2_>No</Message_Waiting_2_>\n")
	arq.write("<Accept_Media_Loopback_Request_2_>automatic</Accept_Media_Loopback_Request_2_>\n")
	arq.write("<Media_Loopback_Mode_2_>source</Media_Loopback_Mode_2_>\n")
	arq.write("<Media_Loopback_Type_2_>media</Media_Loopback_Type_2_>\n\n")

	arq.write("<Ring1_Caller_2_></Ring1_Caller_2_>\n")
	arq.write("<Ring2_Caller_2_></Ring2_Caller_2_>\n")
	arq.write("<Ring3_Caller_2_></Ring3_Caller_2_>\n")
	arq.write("<Ring4_Caller_2_></Ring4_Caller_2_>\n")
	arq.write("<Ring5_Caller_2_></Ring5_Caller_2_>\n")
	arq.write("<Ring6_Caller_2_></Ring6_Caller_2_>\n")
	arq.write("<Ring7_Caller_2_></Ring7_Caller_2_>\n")
	arq.write("<Ring8_Caller_2_></Ring8_Caller_2_>\n")
	arq.write("<Default_Ring_2_>1</Default_Ring_2_>\n")
	arq.write("<Default_CWT_2_>1</Default_CWT_2_>\n")
	arq.write("<Hold_Reminder_Ring_2_>8</Hold_Reminder_Ring_2_>\n")
	arq.write("<Call_Back_Ring_2_>7</Call_Back_Ring_2_>\n")
	arq.write("<Cfwd_Ring_Splash_Len_2_>0</Cfwd_Ring_Splash_Len_2_>\n")

	arq.write("<Cblk_Ring_Splash_Len_2_>0</Cblk_Ring_Splash_Len_2_>\n")
	arq.write("<VMWI_Ring_Policy_2_>New VM Available</VMWI_Ring_Policy_2_>\n")
	arq.write("<VMWI_Ring_Splash_Len_2_>0</VMWI_Ring_Splash_Len_2_>\n")
	arq.write("<Ring_On_No_New_VM_2_>No</Ring_On_No_New_VM_2_>\n")
	arq.write("<Dial_Tone>350@-19,440@-19;10(*/0/1+2)</Dial_Tone>\n")
	arq.write("<Second_Dial_Tone>420@-19,520@-19;10(*/0/1+2)</Second_Dial_Tone>\n")
	arq.write("<Outside_Dial_Tone>420@-16;10(*/0/1)</Outside_Dial_Tone>\n")
	arq.write("<Prompt_Tone>520@-19,620@-19;10(*/0/1+2)</Prompt_Tone>\n")
	arq.write("<Busy_Tone>480@-19,620@-19;10(.5/.5/1+2)</Busy_Tone>\n\n")

	arq.write("<Reorder_Tone>480@-19,620@-19;10(.25/.25/1+2)</Reorder_Tone>\n")
	arq.write("<Off_Hook_Warning_Tone>480@-10,620@0;10(.125/.125/1+2)</Off_Hook_Warning_Tone>\n")
	arq.write("<Ring_Back_Tone>440@-19,480@-19;*(2/4/1+2)</Ring_Back_Tone>\n")
	arq.write("<Ring_Back_2_Tone>440@-19,480@-19;*(1/1/1+2)</Ring_Back_2_Tone>\n")
	arq.write("<Confirm_Tone>600@-16;1(.25/.25/1)</Confirm_Tone>\n")
	arq.write("<SIT1_Tone>985@-16,1428@-16,1777@-16;20(.380/0/1,.380/0/2,.380/0/3,0/4/0)</SIT1_Tone>\n")
	arq.write("<SIT2_Tone>914@-16,1371@-16,1777@-16;20(.274/0/1,.274/0/2,.380/0/3,0/4/0)</SIT2_Tone>\n")
	arq.write("<SIT3_Tone>914@-16,1371@-16,1777@-16;20(.380/0/1,.380/0/2,.380/0/3,0/4/0)</SIT3_Tone>\n")
	arq.write("<SIT4_Tone>985@-16,1371@-16,1777@-16;20(.380/0/1,.274/0/2,.380/0/3,0/4/0)</SIT4_Tone>\n")

	arq.write("<MWI_Dial_Tone>350@-19,440@-19;2(.1/.1/1+2);10(*/0/1+2)</MWI_Dial_Tone>\n")
	arq.write("<Cfwd_Dial_Tone>350@-19,440@-19;2(.2/.2/1+2);10(*/0/1+2)</Cfwd_Dial_Tone>\n")
	arq.write("<Holding_Tone>600@-19;*(.1/.1/1,.1/.1/1,.1/9.5/1)</Holding_Tone>\n")
	arq.write("<Conference_Tone>350@-19;20(.1/.1/1,.1/9.7/1)</Conference_Tone>\n")
	arq.write("<Secure_Call_Indication_Tone>397@-19,507@-19;15(0/2/0,.2/.1/1,.1/2.1/2)</Secure_Call_Indication_Tone>\n")
	arq.write("<Feature_Invocation_Tone>350@-16;*(.1/.1/1)</Feature_Invocation_Tone>\n")
	arq.write("<Ring1_Cadence>60(2/4)</Ring1_Cadence>\n")
	arq.write("<Ring2_Cadence>60(.8/.4,.8/4)</Ring2_Cadence>\n")
	arq.write("<Ring3_Cadence>60(.4/.2,.4/.2,.8/4)</Ring3_Cadence>\n")

	arq.write("<Ring4_Cadence>60(.3/.2,1/.2,.3/4)</Ring4_Cadence>\n")
	arq.write("<Ring5_Cadence>1(.5/.5)</Ring5_Cadence>\n")
	arq.write("<Ring6_Cadence>60(.2/.4,.2/.4,.2/4)</Ring6_Cadence>\n")
	arq.write("<Ring7_Cadence>60(.4/.2,.4/.2,.4/4)</Ring7_Cadence>\n")
	arq.write("<Ring8_Cadence>60(0.25/9.75)</Ring8_Cadence>\n")
	arq.write("<CWT1_Cadence>*(.3/9.7)</CWT1_Cadence>\n")
	arq.write("<CWT2_Cadence>30(.1/.1, .1/9.7)</CWT2_Cadence>\n")
	arq.write("<CWT3_Cadence>30(.1/.1, .1/.1, .1/9.7)</CWT3_Cadence>\n")
	arq.write("<CWT4_Cadence>30(.1/.1,.3/.1,.1/9.3)</CWT4_Cadence>\n")

	arq.write("<CWT5_Cadence>1(.5/.5)</CWT5_Cadence>\n")
	arq.write("<CWT6_Cadence>30(.1/.1,.3/.2,.3/9.1)</CWT6_Cadence>\n")
	arq.write("<CWT7_Cadence>30(.3/.1,.3/.1,.1/9.1)</CWT7_Cadence>\n")
	arq.write("<CWT8_Cadence>2.3(.3/2)</CWT8_Cadence>\n")
	arq.write("<Ring1_Name>Bellcore-r1</Ring1_Name>\n")
	arq.write("<Ring2_Name>Bellcore-r2</Ring2_Name>\n")
	arq.write("<Ring3_Name>Bellcore-r3</Ring3_Name>\n")
	arq.write("<Ring4_Name>Bellcore-r4</Ring4_Name>\n")
	arq.write("<Ring5_Name>Bellcore-r5</Ring5_Name>\n")

	arq.write("<Ring6_Name>Bellcore-r6</Ring6_Name>\n")
	arq.write("<Ring7_Name>Bellcore-r7</Ring7_Name>\n")
	arq.write("<Ring8_Name>Bellcore-r8</Ring8_Name>\n")
	arq.write("<Ring_Waveform>Trapezoid</Ring_Waveform>\n")
	arq.write("<Ring_Frequency>20</Ring_Frequency>\n")
	arq.write("<Ring_Voltage>85</Ring_Voltage>\n")
	arq.write("<CWT_Frequency>440@-10</CWT_Frequency>\n")
	arq.write("<Synchronized_Ring>No</Synchronized_Ring>\n")
	arq.write("<Hook_Flash_Timer_Min>.1</Hook_Flash_Timer_Min>\n")

	arq.write("<Hook_Flash_Timer_Max>.9</Hook_Flash_Timer_Max>\n")
	arq.write("<Callee_On_Hook_Delay>0</Callee_On_Hook_Delay>\n")
	arq.write("<Reorder_Delay>5</Reorder_Delay>\n")
	arq.write("<Call_Back_Expires>1800</Call_Back_Expires>\n")
	arq.write("<Call_Back_Retry_Intvl>30</Call_Back_Retry_Intvl>\n")
	arq.write("<Call_Back_Delay>.5</Call_Back_Delay>\n")
	arq.write("<VMWI_Refresh_Intvl>0</VMWI_Refresh_Intvl>\n")
	arq.write("<Interdigit_Long_Timer>3</Interdigit_Long_Timer>\n")
	arq.write("<Interdigit_Short_Timer>3</Interdigit_Short_Timer>\n")

	arq.write("<CPC_Delay>2</CPC_Delay>\n")
	arq.write("<CPC_Duration>.5</CPC_Duration>\n")
	arq.write("<Call_Return_Code></Call_Return_Code>\n")
	arq.write("<Call_Redial_Code>*07</Call_Redial_Code>\n")
	arq.write("<Blind_Transfer_Code></Blind_Transfer_Code>\n")
	arq.write("<Call_Back_Act_Code></Call_Back_Act_Code>\n")
	arq.write("<Call_Back_Deact_Code></Call_Back_Deact_Code>\n")
	arq.write("<Call_Back_Busy_Act_Code>*05</Call_Back_Busy_Act_Code>\n")
	arq.write("<Cfwd_All_Act_Code></Cfwd_All_Act_Code>\n")
	arq.write("<Cfwd_All_Deact_Code></Cfwd_All_Deact_Code>\n")
	arq.write("<Cfwd_Busy_Act_Code></Cfwd_Busy_Act_Code>\n")
	arq.write("<Cfwd_Busy_Deact_Code></Cfwd_Busy_Deact_Code>\n")
	arq.write("<Cfwd_No_Ans_Act_Code></Cfwd_No_Ans_Act_Code>\n")

	arq.write("<Cfwd_No_Ans_Deact_Code></Cfwd_No_Ans_Deact_Code>\n")
	arq.write("<Cfwd_Last_Act_Code></Cfwd_Last_Act_Code>\n")
	arq.write("<Cfwd_Last_Deact_Code></Cfwd_Last_Deact_Code>\n")
	arq.write("<Block_Last_Act_Code></Block_Last_Act_Code>\n")
	arq.write("<Block_Last_Deact_Code></Block_Last_Deact_Code>\n")
	arq.write("<Accept_Last_Act_Code></Accept_Last_Act_Code>\n")
	arq.write("<Accept_Last_Deact_Code></Accept_Last_Deact_Code>\n")
	arq.write("<CW_Act_Code></CW_Act_Code>\n")
	arq.write("<CW_Deact_Code></CW_Deact_Code>\n")
	arq.write("<CW_Per_Call_Act_Code></CW_Per_Call_Act_Code>\n")
	arq.write("<CW_Per_Call_Deact_Code></CW_Per_Call_Deact_Code>\n")
	arq.write("<Block_CID_Act_Code></Block_CID_Act_Code>\n")
	arq.write("<Block_CID_Deact_Code></Block_CID_Deact_Code>\n")
	arq.write("<Block_CID_Per_Call_Act_Code></Block_CID_Per_Call_Act_Code>\n")
	arq.write("<Block_CID_Per_Call_Deact_Code></Block_CID_Per_Call_Deact_Code>\n")
	arq.write("<Block_ANC_Act_Code></Block_ANC_Act_Code>\n")
	arq.write("<Block_ANC_Deact_Code></Block_ANC_Deact_Code>\n")

	arq.write("<DND_Act_Code></DND_Act_Code>\n")
	arq.write("<DND_Deact_Code></DND_Deact_Code>\n")
	arq.write("<CID_Act_Code></CID_Act_Code>\n")
	arq.write("<CID_Deact_Code></CID_Deact_Code>\n")
	arq.write("<CWCID_Act_Code></CWCID_Act_Code>\n")
	arq.write("<CWCID_Deact_Code></CWCID_Deact_Code>\n")
	arq.write("<Dist_Ring_Act_Code></Dist_Ring_Act_Code>\n")
	arq.write("<Dist_Ring_Deact_Code></Dist_Ring_Deact_Code>\n")
	arq.write("<Speed_Dial_Act_Code>*74</Speed_Dial_Act_Code>\n")
	arq.write("<Paging_Code>*96</Paging_Code>\n")
	arq.write("<Secure_All_Call_Act_Code>*16</Secure_All_Call_Act_Code>\n")
	arq.write("<Secure_No_Call_Act_Code>*17</Secure_No_Call_Act_Code>\n")
	arq.write("<Secure_One_Call_Act_Code>*18</Secure_One_Call_Act_Code>\n")

	arq.write("<Secure_One_Call_Deact_Code>*19</Secure_One_Call_Deact_Code>\n")
	arq.write("<Conference_Act_Code></Conference_Act_Code>\n")
	arq.write("<Attn-Xfer_Act_Code></Attn-Xfer_Act_Code>\n")
	arq.write("<Modem_Line_Toggle_Code>*99</Modem_Line_Toggle_Code>\n")
	arq.write("<FAX_Line_Toggle_Code>#99</FAX_Line_Toggle_Code>\n")
	arq.write("<Media_Loopback_Code>*03</Media_Loopback_Code>\n")
	arq.write("<Referral_Services_Codes></Referral_Services_Codes>\n")
	arq.write("<Feature_Dial_Services_Codes></Feature_Dial_Services_Codes>\n")
	arq.write("<Service_Annc_Base_Number></Service_Annc_Base_Number>\n")
	arq.write("<Service_Annc_Extension_Codes></Service_Annc_Extension_Codes>\n")
	arq.write("<Prefer_G711u_Code>*017110</Prefer_G711u_Code>\n")
	arq.write("<Force_G711u_Code>*027110</Force_G711u_Code>\n")

	arq.write("<Prefer_G711a_Code>*017111</Prefer_G711a_Code>\n")
	arq.write("<Force_G711a_Code>*027111</Force_G711a_Code>\n")
	arq.write("<Prefer_G726r32_Code>*0172632</Prefer_G726r32_Code>\n")
	arq.write("<Force_G726r32_Code>*0272632</Force_G726r32_Code>\n")
	arq.write("<Prefer_G729a_Code>*01729</Prefer_G729a_Code>\n")
	arq.write("<Force_G729a_Code>*02729</Force_G729a_Code>\n")
	arq.write("<FXS_Port_Impedance>600</FXS_Port_Impedance>\n")
	arq.write("<FXS_Port_Input_Gain>-3</FXS_Port_Input_Gain>\n")
	arq.write("<FXS_Port_Output_Gain>-3</FXS_Port_Output_Gain>\n")

	arq.write("<DTMF_Playback_Level>-16</DTMF_Playback_Level>\n")
	arq.write("<DTMF_Playback_Length>.1</DTMF_Playback_Length>\n")
	arq.write("<Detect_ABCD>Yes</Detect_ABCD>\n")
	arq.write("<Playback_ABCD>Yes</Playback_ABCD>\n")
	arq.write("<Caller_ID_Method>Bellcore(N.Amer,China)</Caller_ID_Method>\n")
	arq.write("<Caller_ID_FSK_Standard>bell 202</Caller_ID_FSK_Standard>\n")
	arq.write("<Feature_Invocation_Method>Default</Feature_Invocation_Method>\n")
	arq.write("<Protect_IVR_FactoryReset>No</Protect_IVR_FactoryReset>\n")
	arq.write("<Max_Session>2</Max_Session>\n")

	arq.write("<Enable_WAN_Web_Server>Yes</Enable_WAN_Web_Server>\n")
	arq.write("<Web_Management><Web_Utility_Access_HTTP>1</Web_Utility_Access_HTTP></Web_Management>\n")
	arq.write("<Networking_Service>Bridge</Networking_Service>\n\n")

	if dado.prov_mac.ip == "" or dado.prov_mac.ip == None:
		arq.write("<Connection_Type>DHCP</Connection_Type>\n")
		arq.write("<DHCP>Yes</DHCP>\n\n")
	else:
		arq.write("<Connection_Type>Static IP</Connection_Type>\n")
		arq.write("<DHCP>No</DHCP>\n\n")

	arq.write("<Static_IP>%s</Static_IP>\n" %(dado.prov_mac.ip))
	arq.write("<NetMask>%s</NetMask>\n" %(dado.prov_mac.mascara))
	arq.write("<Gateway>%s</Gateway>\n" %(dado.prov_mac.gateway))
	arq.write("<Primary_DNS>%s</Primary_DNS>\n" %(dado.prov_rede.dns))
	arq.write("<Primary_NTP_Server>%s</Primary_NTP_Server>\n\n" %(dado.prov_rede.ntp))

	if dado.prov_mac.vlan == "" or dado.prov_mac.vlan == None:
		arq.write("<Enable_VLAN>No</Enable_VLAN>\n")
		arq.write("<VLAN_ID>1</VLAN_ID>\n")
	else:
		arq.write("<Enable_VLAN>Yes</Enable_VLAN>\n")
		arq.write("<VLAN_ID>%s</VLAN_ID>\n\n" %(dado.prov_mac.vlan))

	arq.write("<HostName>SPA2102</HostName>\n")
	arq.write("</flat-profile>\n")
	arq.close()
	return (True, 'ok')




